# Generated by Django 6.0.2 on 2026-02-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Unique device identifier (e.g., bed_12_node)', max_length=100, unique=True)),
                ('bed_number', models.CharField(help_text='Associated bed number', max_length=50)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='OFFLINE', help_text='Current device status', max_length=10)),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Last time the device was active')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['bed_number', 'device_id'],
            },
        ),
    ]
