# Generated by Django 6.0.2 on 2026-02-21 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_node', '0001_initial'),
        ('patients', '0002_patient_past_medical_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestVitals',
            fields=[
                ('patient', models.OneToOneField(help_text='Patient for these vital signs', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='latest_vitals', serialize=False, to='patients.patient')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Body temperature in Celsius', max_digits=4, null=True)),
                ('heart_rate', models.IntegerField(blank=True, help_text='Heart rate in BPM', null=True)),
                ('spo2', models.IntegerField(blank=True, help_text='Blood oxygen saturation percentage', null=True)),
                ('risk_level', models.CharField(blank=True, default='', help_text='Calculated risk level (e.g., LOW, MEDIUM, HIGH)', max_length=20)),
                ('trend', models.CharField(choices=[('STABLE', 'Stable'), ('RISING', 'Rising'), ('FALLING', 'Falling')], default='STABLE', help_text='Vital signs trend', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
            ],
            options={
                'verbose_name': 'Latest Vitals',
                'verbose_name_plural': 'Latest Vitals',
                'ordering': ['-updated_at'],
            },
        ),
    ]
