# Generated by Django 6.0.2 on 2026-02-21 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_node', '0003_prediction'),
        ('patients', '0002_patient_past_medical_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HIGH_RISK', 'High Risk'), ('WARNING', 'Warning'), ('DEVICE_OFFLINE', 'Device Offline')], help_text='Alert type/category', max_length=20)),
                ('message', models.TextField(help_text='Alert message/description')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], help_text='Alert severity level', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the alert is still active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this alert was created')),
                ('patient', models.ForeignKey(help_text='Patient this alert is for', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', '-created_at'], name='bed_node_al_patient_4e7f83_idx'), models.Index(fields=['is_active', '-created_at'], name='bed_node_al_is_acti_fec96b_idx'), models.Index(fields=['type', 'severity'], name='bed_node_al_type_0c44cc_idx')],
            },
        ),
    ]
