# Generated by Django 6.0.2 on 2026-02-21 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bed_node', '0004_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestvitals',
            name='trend',
        ),
    ]
