# Generated by Django 6.0.2 on 2026-02-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_node', '0005_remove_latestvitals_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestvitals',
            name='ai_analysis',
            field=models.TextField(blank=True, default='', help_text='AI-generated analysis and recommendations from Gemini'),
        ),
    ]
