# Generated by Django 6.0.2 on 2026-02-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_node', '0006_latestvitals_ai_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='ai_analysis',
            field=models.TextField(blank=True, default='', help_text='AI-generated context and recommendations for this alert'),
        ),
    ]
