# Generated by Django 6.0.2 on 2026-02-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Hospital name', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Registration timestamp')),
            ],
            options={
                'db_table': 'hospitals',
                'ordering': ['name'],
            },
        ),
    ]
