# Generated by Django 6.0.2 on 2026-02-21 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(help_text='Human-readable patient ID (e.g., PAT_0045)', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, help_text='Patient name (optional for demo)', max_length=255, null=True)),
                ('bed_number', models.CharField(help_text='Bed number assigned to patient', max_length=50)),
                ('ward', models.CharField(help_text='Ward where patient is located', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Patient admission timestamp')),
                ('hospital', models.ForeignKey(help_text='Hospital where patient is admitted', on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='hospitals.hospital')),
            ],
            options={
                'db_table': 'patients',
                'ordering': ['-created_at'],
                'unique_together': {('bed_number', 'hospital')},
            },
        ),
    ]
