# Generated by Django 6.0.2 on 2026-02-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='past_medical_records',
            field=models.TextField(blank=True, help_text='Past medical history and records', null=True),
        ),
    ]
